"""empty message

Revision ID: 0c31bb3b251b
Revises: bbfb419e9767
Create Date: 2024-01-06 13:02:18.556456

"""
from alembic import op
import sqlalchemy as sa


import os

environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '0c31bb3b251b'
down_revision = 'bbfb419e9767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('street_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('apartment', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(), nullable=True))

        if environment == "production":
            op.execute(f"ALTER TABLE orders SET SCHEMA {SCHEMA};")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('zip_code')
        batch_op.drop_column('city')
        batch_op.drop_column('apartment')
        batch_op.drop_column('street_address')
        batch_op.drop_column('full_name')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
