"""empty message

Revision ID: 9dfe05f9342e
Revises: 0c8d2395b1e5
Create Date: 2023-12-24 08:40:27.677947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfe05f9342e'
down_revision = '0c8d2395b1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mileage', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('mileage')

    # ### end Alembic commands ###
